### ISSUE TITLE
"Find Exact Matches" progress dialogue does not get validated

### ISSUE THREAD

**Issue by touwys** [Borewit/listFix#100]
**listFix() v2.6.0 | Windows 7 x64**

The progress dialogue for "Find Exact Matches" (binoculars) completes without any form of validation. What are the results the user should expect to see from it?

!['Select Closest' matches calls two dialogues](https://user-images.githubusercontent.com/65730626/219944700-9a0b5f81-d702-4f7c-ab91-f457711a33be.gif)

**Comment by Borewit** [comment]
This function no longer exists.
