### ISSUE TITLE
Improve the behavior of the dual progress bar

### ISSUE THREAD

**Issue by Borewit** [Borewit/listFix#109]
The dual progress bar shows progress of execution one or more background tasks (sub-tasks).
The total progress is the progress of the tasks, where the second progress bar shows the progress of the current background tasks being executed.

**Current behavior** is that the total progress-bar counts the sub-task as completed before it's even started.
If there is sub-single task to be completed , it immediately jumps to completed. 

**Expected behavior** 
The progress of the sub-tasks, steers relative progress of total.
So if there are 4 sub-tasks to perform.
So the total progress is calculated as:
total-progress = subtasks completed * (100% / number-of-subtasks) + progress-current-subtask * (100% / number-of-subtasks)

**Comment by touwys** [comment]
@Borewit, does this issue perhaps also refer back to https://github.com/Borewit/listFix/issues/99?
