### ISSUE TITLE
Support for drag and drop selected playlist(s) from location into Playlist Directory (PLD)

### ISSUE THREAD

**Issue by touwys** [Borewit/listFix#117]
We now have support for dragging and dropping playlist folders directly into the PLD — as from [listFix_2.6.0-PR113-5](https://github.com/Borewit/listFix/pull/113) .

🛠️ Please, provide support also for dragging and dropping selected **Playlist(s)** from their location to the PLD. 

If this option is infeasible, could the support move refocus to open single, or multiple, selected playlists into the Playlist Editor, direct from their location in the operating system explorer?

**Comment by Borewit** [comment]
It is not logical to accept playlists in the Playlists-Directories as that is to manage playlist directories and not playlists.

Yes I can just open the playlist in an editor, but what did you user try to do with that drag? Maybe copy a file into the playlist directory?  

If the file is dragged onto the playlist editor pane, I am all for it.

**Comment by Borewit** [comment]
Maybe this issue is actually a bug, as the intention was clearly to make this possible, there is existing code for this stuff, but like #113, it just had to be fixed.

**Comment by touwys** [comment]
The logic behind it cuts both ways, because, clearly, the playlists that are getting dragged and dropped here, simply occupy the same space as those that reside in folders. Their folders just reside elsewhere on disc, not visible as the others. Likewise, the same extended operations can be performed on them, as for those playlists that occupy the folders. Therefore, it will not bother me at all to have them added to the PLD. In fact, I would really welcome such a move.

**Comment by touwys** [comment]
Bear in mind though, this as a possible clash: See https://github.com/Borewit/listFix/pull/106#issuecomment-1448156205

**Comment by Borewit** [comment]
Dragging playlist(s) are accepted by the _Playlist Editor_ (#143), but shall not be accepted by the _Playlists Directory_, as there is not logical way of handling a playlist in the _Playlists Directory_.
