### ISSUE TITLE
Exception thrown calculating relative playlists path

### ISSUE THREAD

**Issue by Borewit** [Borewit/listFix#122]
When the use-relative-path options is enable, it may break fixing playlists in combination with absolute path and UNC paths.
```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: 'other' is different type of Path
````

**Comment by touwys** [comment]
> When the use-relative-path options is enable, it may break fixing playlists in combination with absolute path and UNC paths.

_If it's not too much trouble, would you please explain the following:_ 

1. Why would the user enable the listFix() option to `Save playlists with relative file references`? 

2. How does the user determine whether his media library applies UNC-paths — if, perhaps, he should want to enable the listFix() option `Media library uses UNC paths for directories on mapped drives`?

**Comment by Borewit** [comment]
> Why would the user enable the listFix() option to Save playlists with relative file references?

There are many good reasons for that:
1. It prevents breaking the playlist, together with the content to another folder. For example, let's imagine you have a playlist like 
```
CD1\track1.flac
CD2\track8.flac
```
versus absolute paths:
```
C:\My music\Artist\CD1\track1.flac
C:\My music\Artist\CD2\track8.flac
```
2. In a network drive the absolute path may different depending the way you access you music.
When I store music on my Synology with absolute filename, software running on the Synlolgy itself would not understand the absolute file names:
```
\\diskstation\music\Album3\track4.mp3
\\diskstation\music\Album4\track5.mp3
```
As on the Synology the paths are:
```
/volume1/music/Album3/track4.mp3
/volume1/music/Album4/track5.mp3
```
Even though it are still Windows style path, it does understand:
```
..\Album3\track4.mp3
..\Album4\track5.mp3
```
stored in `\\diskstation\music\#playlist`

> 2 How does the user determine whether his media library applies UNC-paths — if, perhaps, he should want to enable the listFix() option Media library uses UNC paths for directories on mapped drives?

This is only relevant if you store files on a remote Windows file server.
So saving in UNC basically means you prevent using the mounted driver letters.

If I mount `\\diskstation\music` as `M:\`, listFix() will convert `M:\` to UNC style, which is `\\diskstation\music`.
On a different host, which may not have the M drive, or mounted  `\\diskstation\music` to a different drive, the tracks will still be found.

**Comment by touwys** [comment]
Thank you for a very good explanation.

At the very moment (and there is still a very long way to go), I am busy renewing my media library. One of the reason is to do just that: to shorten the absolute paths. From what I learn now, it seems it's best policy for the user to keep the relative path option in listFix() enabled. But, for testing purposes, is it better to leave this disabled?

As far as UNC files is concerned, the media library is stored locally, so no need for that.

Thanks again. 🤝
