### ISSUE TITLE
Drop the "Exact Matches Repair...." feature 

### ISSUE THREAD

**Issue by touwys** [Borewit/listFix#154]
The "Repair" menu could be trimmed by removing the first entry, namely: "Exact Matches Repair". This action is already more suitably taken care of in the editor, and it does not really belong here with the other two. 

![image](https://user-images.githubusercontent.com/23255260/229868183-6dedeeae-37fa-480f-bf8a-3066f2d88dc2.png)

**Comment by Borewit** [comment]
I noticed there is different terminology:

There are 2 methods of fixing playlists:
1. Unresolved playlist entries are automatically replaced with closest match found
2. Unresolved playlist entries are shown with a number of alternative, sorted by the closest match 


Via the "Playlist Editor", method # 1,  Fix everything
Via the "Playlist Editor", method # 1,  Find Exact Match

Via the "Playlist Directories", method # 1, "Quick", "Quick Batch Repair"
Via the "Playlist Directories", method # 2, "Deep", "Deep Batch Repair"

Where "Quick Batch Repair" can handle multiple playlists (batch) selected in the playlist directories
Where "Deep Batch Repair" can handle multiple playlists (batch) selected in the playlist directories

Via the Repair menu:
 "Quick Repair Currently Opened Playlists", uses method # 1, in batch mode on all open playlists in editor
 "Deep Repair Currently Opened Playlists", uses method # 2, in batch mode on all open playlists in editor

And then there is the "Exact Matches Repair....", which based on picking a file (or more, did not try). It indeed does not make sense to me. I have no problem cutting that one out.

I am summarizing all of this, as I am not fan of the terminology.

Also strongly related to:
- #41

**Comment by touwys** [comment]
> I noticed there is different terminology:

Yes, I also noticed that. It puzzles me why it has been done that way, because, for the user, the different descriptions seem to infer slightly different processes, and that can be quite confusing.
 
It will certainly represent a huge improvement, once you have fixed that.

**Comment by touwys** [comment]
Addendum: Are you perhaps considering to strip all the other editing access points, and limit it to the most suitable one, the Playlist Editor?

**Comment by Borewit** [comment]
> Addendum: Are you perhaps considering to strip all the other editing access points, and limit it to the most suitable one, the Playlist Editor?

That is indeed what more or less what I had in mind in #41. It's quite a chunk of work we trash, but don't see a lot of added values in the "batched" modes.

What do you think about that @touwys?

**Comment by touwys** [comment]
> It's quite a chunk of work we trash, but don't see a lot of added values in the "batched" modes.

Personally, I do actually find the batch mode quite useful. Once the exact matches command is dropped, can the select closest matches **batch mode** not be moved to the Editor?

**Comment by Borewit** [comment]
> Personally, I do actually find the batch mode quite useful.

So let's fix the cancellation, like you suggested in #155.

> can the select closest matches batch mode not be moved to the Editor?

The scope of the Playlist Editor Toolbar are buttons for functions which apply to that playlist only. So I don't think that makes it better.

**Comment by touwys** [comment]
> So let's fix the cancellation, like you suggested in #155.

But the terminlogy still are to be fixed for uniformity's sake?

> The scope of the Playlist Editor Toolbar are buttons for functions which apply to that playlist only. So I don't think that makes it better.

Yes, I do realise that, but I was thinking in line of this [**proposal**](https://github.com/Borewit/listFix/issues/69), which sees that the tab-functions are eventually extended.
