### ISSUE TITLE
Unexpected hang during initialize UI Splash screen.

### ISSUE THREAD

**Issue by vall77** [Borewit/listFix#16]
On Linux Mint 20.3
Using gradle 5.6 with Java SE 13 the build was successful in 31 seconds
but encountered an exception in thread Main it has been executing for 1 hour and 22 minutes hanging on the splash screen during the initialize UI(Frozen).

Assistance would be appreciated thank you for Reviving this project.

![image](https://user-images.githubusercontent.com/35142891/171324633-a2f28cf3-4b19-4fa4-b112-357b13482679.png)
![image](https://user-images.githubusercontent.com/35142891/171324568-f136f7d0-afd4-43b2-93c6-7cd1aaa32f75.png)
![image](https://user-images.githubusercontent.com/35142891/171324888-2e198744-3bcd-4ae3-9242-e04cc9023e2c.png)

**Comment by Borewit** [comment]
I think because [listFix()](https://github.com/Borewit/listFix) as depends on Microsoft Windows.

**Comment by vall77** [comment]
It was working on Linux Mint 19.03 but I updated and now it hangs

**Comment by Borewit** [comment]
I had issues working with SDK > 15, but mostly running the distributions.
Did you try the latest code?

It looks like some dependencies are missing in your screenshot, so I suspect for some reason your current SDK is missing something. If you try [OpenJDK JDK 15 Project](https://jdk.java.net/java-se-ri/15)?

**Comment by Borewit** [comment]
@vall77, try: 
```shell 
java --add-exports java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED -jar listFix-2.5.1-all.jar
```

Related: https://stackoverflow.com/questions/62990097/openjdk-11-class-not-found-error-com-sun-java-swing-plaf-windows-windowslookand

**Comment by Borewit** [comment]
Only tried it on Windows, I could not get the 2.5.1 to work.
Maybe due to deprecated dependencies. 

Starting the current jar build https://github.com/Borewit/listFix/commit/72f962748f5410004fea7390fe01b51d087e0275 worked for me on on Windows: [listFix-2.5.1-8-all](https://www.mediafire.com/file/6zwx3e0e9o5rpqe/listFix-2.5.1-8-all.jar/file)

I need still need to try on Linux though...

**Comment by vall77** [comment]
Oh heck!
It works!
It's been 2 years since I've been able to get this program to work and you fixed it!
I can finally find my favorite songs, I have a large media library 50 GB worth of audio.

![Screenshot_it_works](https://user-images.githubusercontent.com/35142891/217444629-4826aca3-c4dd-40cc-9c49-d0c746cad7fe.png)

Just fixed my first playlist, I'm so emotional all the songs are right here.

**Comment by Borewit** [comment]
I keep this issue open until there is a formal released jar as part of the next distribution.
