### ISSUE TITLE
Upon changing the skin, the app hangs

### ISSUE THREAD

**Issue by touwys** [Borewit/listFix#17]
**Steps:**

- Go to File
- Choose Options
- Choose Look & Feel
- Choose any option (or don't)
- Click OK
- App hangs indefinitely and has to be forcefully closed

**Device:**

- Windows 7 x 64 PC
- listFix v2.4.0

Screen video:

•
•

![listFix hangs on changing skin option](https://user-images.githubusercontent.com/65730626/211782936-e50bca0f-3d96-4855-85a3-8770191c9abf.gif)

**Comment by Borewit** [comment]
Reported as being resolved in [v2.4.2](https://github.com/Borewit/listFix/releases/tag/v2.4.2) as reported https://github.com/Borewit/listFix/pull/19#issuecomment-1383740584.
