### ISSUE TITLE
Review the renegade (deep, batch) repair function

### ISSUE THREAD

**Issue by Borewit** [Borewit/listFix#207]
> Yes, agree, that's a total renegade operation. That deserves, _Are you really, really sure you want to run this?_ confirmation. Maybe to get rid of it?

Well said. Then, the real question facing us is whether this "renegade" is to be welcomed, or whether it should be expelled. We have to consider whether it substantially contributes towards the overall functionality and performance of the app, in addition to whether an alternative path exists with which to achieve the same end. Even though the answers to these questions appear clear to me, I am going to leave the adjudication up to you, the developer, for you have the broader overview of its impact. 

***

_Originally posted by @touwys in https://github.com/Borewit/listFix/issues/177#issuecomment-1733147508_

![image](https://github.com/Borewit/listFix/assets/23255260/a6e0d646-1e5f-43c1-b222-2b17e11382b1)

**Comment by Borewit** [comment]
This "Deep Repair" is performed on every playlist selected in the _Playlists Directory_ panel.

I believe it essentially looks for each broken playlist entries, and applies the best match algorithm to any of those.

It confuses me that a different methodology of repairing is applied here. If you want to fix playlists with a lot of them together, why is the end result more manual. It's a competing conception. 

I don't know at how many places I already deduplicated algorithm, and here are again nearly the same loops.

![image](https://github.com/Borewit/listFix/assets/23255260/c26a5b86-c29c-4b72-bbf7-c22479f1a16f)

**Comment by touwys** [comment]
Is it not possible to tell from the code alone, what is supposed to happen during this repair, and what is to be expected from it? Until the methodology is more fully comprehended, it may be prudent to _not_ discard the "Deep Repair" function — in case the mechanism is needed sometime ahead.

**Comment by Borewit** [comment]
> Is it not possible to tell from the code alone

It certainly is, but it is very time consuming analysis.
I think it is much easier to figuring out by trying it on a few broken playlists, and if required look deeper in the code on bits which are not clear.

What is I believe it does is using the closest-match algorithm proposing changes to selected playlists. So in the dialog you can pick each of the playlists which you have selected, and each playlist entries has the top 20 (unless overwritten in config with another number) sorted on the best match first. Either you override the selection by picking another entry from the best match selection, or you leave things as they are. When you hit Save All Repairs, it probably same everything according to the selection.

**Comment by touwys** [comment]
> It certainly is, but it is very time consuming analysis. I think it is much easier to figuring out by trying it on a few broken playlists, and if required look deeper in the code on bits which are not clear.

I subscribe to that.

> What is I believe it does is using the closest-match algorithm proposing changes to selected playlists. So in the dialog you can pick each of the playlists which you have selected, and each playlist entries has the top 20 (unless overwritten in config with another number) sorted on the best match first. Either you override the selection by picking another entry from the best match selection, or you leave things as they are. When you hit Save All Repairs, it probably same everything according to the selection.

Have never utilised this feature, so it's hard to comment at all.
