### ISSUE TITLE
Support for "Remove playlist" from the Playlists Directories

### ISSUE THREAD

**Issue by touwys** [Borewit/listFix#230]
`Go to "Playlists Directories > Select a playlist > Right-click on it to open the context menu:`

Just as with playlist directories, it is desirable not to delete a playlist, but to be able to simply remove it from view in the PD-pane.
 
It is therefore proposed that the menu entry "Remove playlist directory" changes to "Remove playlist" as a means to fullfil this action.

•

![image](https://github.com/Borewit/listFix/assets/65730626/a138d7ba-ceeb-48e4-ab34-10c658e9c6fd)

**Comment by Borewit** [comment]
Removing a playlist from that selection is not that simple, it would require to keep some kind of state which playlists are visible, or which playlists have been removed. The next issue will be, a user totally confused he can longer load a playlist in a given directory. I am not going to that, things become unnecessary complicated.

We can just hide that option if a playlist is selected.

**Comment by touwys** [comment]
> Removing a playlist from that selection is not that simple, it would require to keep some kind of state which playlists are visible, or which playlists have been removed.

Thank you for straightening it out. The proposal stemmed from absent insight within the app-framework, its fabric, so to speak, and the probable side effects, or issues, it may cause further downstream, at user-level.

> We can just hide that option if a playlist is selected.

It appears to be a superfluous transfer from the Playlists Directories context menu. Agree, it's unnecessary.
