### ISSUE TITLE
The "Find Exact Matches" action appears to be dysfunctional?

### ISSUE THREAD

**Issue by touwys** [Borewit/listFix#28]
@Borewit: Re listFix() v2.4.2:

I am not at all sure about this, but selecting "Find Exact Matches" to fix a broken list appears to not deliver what resembles a result, or flag a clue of some sort. It does briefly display the progress window, though. Screen video below.

_In addition, do I post any questions etc, I may have about the app in general, here under issues, or perhaps elsewhere?_

Thank you.

![image](https://user-images.githubusercontent.com/65730626/212715556-0edc626c-249d-47ed-bc34-97bfcaf382d7.gif)

**Comment by Borewit** [comment]
> In addition, do I post any questions etc, I may have about the app in general, here under issues, or perhaps elsewhere?

Opening a new issue was the right thing, like you have done now was the right thing to do. In principle every question in new issue, unless it is about one an the same thing. 

If you want to chat, I created a [Discord channel](https://discord.gg/cP4BmJfQ).

**Comment by Borewit** [comment]
~~!!I think the "Find Exact Matches" is not repair the playlist, it only to update the status~~ ![image](https://user-images.githubusercontent.com/23255260/212740979-571ce41f-7a0c-44e1-b95c-c89247e99af9.png) / ![image](https://user-images.githubusercontent.com/23255260/212741029-756c470d-bb0e-448c-9599-efe7585e8d97.png).

~~The "Fix Everything" is. The misleading part is that the dialog holding the progress-bar says "repairing".~~

**Comment by touwys** [comment]
> If you want to chat, I created a [Discord channel](https://discord.gg/cP4BmJfQ).

Thank you very much, @Borewit. Let's see how it goes. Maybe later? Are you perhaps on Telegram, as well? I can join you on the latter, already.

**Comment by Borewit** [comment]
@touwys , [you reported it did work when you created a playlist with some audio tracks on `C:\`](https://github.com/Borewit/listFix/pull/19#issuecomment-1407709215). I can only fix the issue, if I can reproduce the issue. To be able to reproduce this issue, I need to understand under what condition the issue occures. Can you migrate the test environment, step by step, towards the condition in which it breaks. What happens when you select your original drive as the media directory? What happens if you move the playlist? What type of drive (USB, HDD, network) are you using, when it breaks? Please proceed testing with [v2.5.0](https://github.com/Borewit/listFix/releases/tag/v2.5.0).

In the mean time, I will work on a log file (#35), and eliminate suppressed exceptions, so I can hopefully find an exception somewhere.

**Comment by touwys** [comment]
I was already planning to carry on testing along the lines you propose. It makes sense that way. I'll start by copying the same files with their playlist to several other drives, and take it from there.

**Comment by touwys** [comment]
I am reporting my findings on listFix_2.5.0 as issues, OK?

**Comment by touwys** [comment]
**Testing listFix_2.5.0**

I find myself chasing windmills. I am quite uncertain at the moment about the way certain actions, when executed, are expected to behave. The nomenclature is confusing, to say the least. Underneath, there follows is a screenshot of one such example: 

For instance: Are "Exact Matches Repair" (Ctrl + M) and "Find Exact Matches" one and the same thing — only they are accessible from two different locations? As they stand now, their actions do not match.

_Observation: I made two different playlists. One for a single disc taken from a multi-disc box set, and one for a number of tracks that I randomly selected. I proceeded to move the playlist out of their respective folders in order to break the list-to-track relationship, and then I copied the two test folders over to the roots of three different hard drives, plus one test-folder copied to a subdirectory on one of the drives. All the test playlists repaired properly. It should be noted that even the "Find Exact Matches" (binocular icon) action turned in **fully repaired playlists**. However, when the same "Find Exact Matches" (binocular icon) action is executed on previously made, older playlists, it still behaves as reported before — for all the releases tested up to now. This issue appears to be one that needs to be ironed out, and any suggestions on what the cause might be and how to proceed to nail it down, are welcome indeed._

•
 👉 [SCREENSHOT](https://user-images.githubusercontent.com/65730626/215511156-ff346f2f-b7df-47d5-9426-d9e5a49f67da.png)
• 

**Question:**

**"Exact Matches Repair" (Ctrl + M):** Screenshot of action-window which opens. What action is required here, which is not already available elsewhere? Does it only open a playlist to repair in some way other than what is already available?

• 
 👉 [SCREENSHOT](https://user-images.githubusercontent.com/65730626/215513223-a2add561-bcfc-43da-a265-1901a687a08f.png)
•

**Comment by Borewit** [comment]
> However, when the same "Find Exact Matches" (binocular icon) action is executed on previously made, older playlists, it still behaves as reported before

Can you try to isolate the error condition?

It is probably either the playlist, or the media-library configuration causing the error.

If you try to fix another playlist using the same media-library configuration, does it still fail as well?
If change the media-library configuration to a sub-directory, does it still fail?

What type of playlist is it? iTunes is probably broken in the last releases, fixed that in #36 (not in any release yet).

**Comment by touwys** [comment]
Thank you for your dedication to this job, @Borewit 

> Can you try to isolate the error condition?

I am going to give this a bash tomorrow.

> What type of playlist is it? iTunes is probably broken in the last releases, fixed that in #36 (not in any release yet).

All my playlists are "m3u" — none of iTunes. These are almost exclusively generated by MusicBee, my one-stop music library manager since its inception. It is an extraordinary accomplished application, and I can't truly think of any way its configuration can interfere to cause this issue, although anything is possible. I made the two test playlists with it too, today.

**Comment by Borewit** [comment]
I have [released a version 2.5.1 with logging enabled](https://github.com/Borewit/listFix/releases/tag/v2.5.1). 

Hopefully that provides some more clarity on this issue.

For easier monitoring of the log file, you mind want to try [Notepad++](https://notepad-plus-plus.org/downloads/).

**Comment by touwys** [comment]
**Testing listFix() v2.5.1**

_Two procedures were tested:_

1. "Find Exact Matches" (by applying the binocular icon on the toolbar.)
2. The new error(?) log files — copies of which are attached. 

**Test Results:**

**_2. Log files_**

The messages of the two log files are identical(?), and they appear to be incomplete, thus inconsequential for error tracking?
•
[logfile.log](https://github.com/Borewit/listFix/files/10543698/logfile.log)
[rollingfile.log](https://github.com/Borewit/listFix/files/10543699/rollingfile.log)
•

**_1. "Find Exact Matches"_**

1.1 The media files and playlists that were used for this particular test, are all stored on the same internal HDD, on which the music library is stored. All programme files, including listFix(), are located on an SSD.

1.2 All the playlists, used in this test, were produced by [MusicBee](https://getmusicbee.com/), the Library Manager. 

1.3 The first attempt to "Find Exact Matches" failed, as can be seen in the first screen video. It still only flashes a progress window, titled "Repairing", across the screen. However, applying "Fix Everything" (magic wand), opens the "Select Closest Matches" window, which locates and matches the missing tracks. 

1.4 The second attempt to "Find Exact Matches" succeeded 100%, as can be seen in the second screen video. What changed? —

1.4.1 The same set of tracks were re-assembled in the MusicBee player.

1.4.2 A copy of this set of tracks was exported to a different folder, located elsewhere, but on the same HDD on which the music library is kept.

1.4.3 The playlist for this set of tracks was then separated and placed just outside the folder keeping the tracks, to break the playlist-file relationship.

•
[Screen Video: listfix 2 5 1 test broken playlist _ does NOT find exact matches](https://user-images.githubusercontent.com/65730626/215713213-504690ad-e14d-4627-9386-e39d31b80f5e.gif)
[Screen Video: listfix 2 5 1 test broken playlist _ does find exact matches](https://user-images.githubusercontent.com/65730626/215713299-cd1cb732-9feb-4403-811d-420b47ba7189.gif)
•

**Comment by Borewit** [comment]
The log file is working for you, because we see the initial log message on INFO level. So that is something.

> The messages of the two log files are identical(?),
 `rollingfile.log` is more verbose then `logfile.log`. They can be each configured with their [own log levels](https://logging.apache.org/log4j/2.x/manual/customloglevels.html).
 
Secondly the  `rollingfile.log` is limited in size. So just after a crash, `rollingfile.log` is probably the best choice.

However, hardly anything else then exceptions are logged, so at this moment there is no difference between the 2 files. 

But, yes there is no exception in the log (ERROR level), which I hoped for,
So that means either there is no exception thrown, or there is still code which ignores the exception, without even logging it.

> 1.4.1 The same set of tracks were re-assembled in the MusicBee player.

> 1.4.2 A copy of this set of tracks was exported to a different folder, located elsewhere, but on the same HDD on which the music library is kept.

What if you just copy the playlist to new location, does it break?

I will enable more detailed log messages, hopefully that gives more clarity.

**Comment by Borewit** [comment]
@touwys, can you try this build: #46, with more verbose logging enabled.

**Comment by touwys** [comment]
> But, yes there is no exception in the log (ERROR level), which I hoped for

👍

> What if you just copy the playlist to new location, does it break?

I copied the playlist over, on its own, from the HDD where the music files are housed to the SSD. Resultsof trying to repair this playlist are shown in the two screen videos below:

**"Find Exact Matches" Failed**
 
👉 [SCREEN VIDEO: listfix 2 5 1 find exact matches _ 20230131](https://user-images.githubusercontent.com/65730626/215772300-98bca371-a971-46e9-9612-e2410425d3db.gif)
•
**"Fix Everything" Succeeded** _(I cancelled the repair operation before completion to shorten the video)_

 👉 [SCREEN VIDEO: listfix 2 5 1 fix everything _ 20230131](https://user-images.githubusercontent.com/65730626/215772771-ec1a8fe5-0715-4c57-940c-a25b77aa2eae.gif)

**Comment by touwys** [comment]
> can you try this build: #46, with more verbose logging enabled.

Downloaded. Any reason why, in this particular case, I should not install this version over 2.5.1? I do not mind, otherwise.

**Comment by touwys** [comment]
**listFix_2.5.1-1 Test "Find Exact Matches"**
•
[listfix_2.5.1-1 _ logfile.log](https://github.com/Borewit/listFix/files/10547126/listfix_2.5.1-1._.logfile.log)
[listfix_2.5.1-1 _ rollingfile.log](https://github.com/Borewit/listFix/files/10547128/listfix_2.5.1-1._.rollingfile.log)
•

**Comment by Borewit** [comment]
> Any reason why, in this particular case, I should not install this version over 2.5.1

No

Interesting, so the log file basically says everything has been repaired, but you graphical user interface just hangs for some mysterious reason. Hmm, maybe I need to look closer into that progress dialog.

The `rolingfile.log` is sufficient for future log files, and you can always cut the last portion starting at `Starting ListFix()...`

**Comment by touwys** [comment]
> Interesting, so the log file basically says everything has been repaired, but you graphical user interface just hangs for some mysterious reason. Hmm, maybe I need to look closer into that progress dialog.

_The playlist is **not** getting repaired using "Find Exact Matches":_  🤔

After the "Repairing" progress window has run its course, first, there is no graphical indication, i.e. the "OK" icon next to the tracks, to indicate that the repair has been effected. Second, graphics aside, in order to verify whether the playlist was in fact repaired, or not, I saved the playlist after the process "Find Exact Matches" > "Repairing" has completed. The intended "repaired" playlist was finally opened in the music player to play, but it was still completely broken, so it did not play.

**Comment by touwys** [comment]
@Borewit :

Do you perhaps want me to run additional tests for you, regarding the "Find Exact Matches" issue? I am all out of ideas. 🙃

**Comment by Borewit** [comment]
This function no longer exists
