### ISSUE TITLE
"Fix Everything" Error

### ISSUE THREAD

**Issue by touwys** [Borewit/listFix#29]
In applying the "Fix Everything" command on a broken playlist, the error message, as depicted in the screenshot below, gets flagged. 

- Device: PC
- OS: Windows 7 x64
- listFix(): v2.4.2-3 

[Also see #19 ](https://github.com/Borewit/listFix/pull/19#issuecomment-1396550686)

_Note: I am not sure whether I should report issues here too._

**Error Screenshot:**

![image](https://user-images.githubusercontent.com/65730626/213429945-7fee3e94-0f78-4405-a41a-b4753ec3691c.png)

**Comment by Borewit** [comment]
Introduced by PR #19 which not merged yet.

See also: https://github.com/Borewit/listFix/pull/19#issuecomment-1407692395
