### ISSUE TITLE
Redundant ways to open and repair a playlists 

### ISSUE THREAD

**Issue by Borewit** [Borewit/listFix#41]
**Testing listFix_2.5.0**

I find myself chasing windmills. I am quite uncertain at the moment about the way certain actions, when executed, are expected to behave. The nomenclature is confusing, to say the least. Underneath, there follows is a screenshot of one such example: 

For instance: Are "Exact Matches Repair" (Ctrl + M) and "Find Exact Matches" one and the same thing — only they are accessible from two different locations? As they stand now, their actions do not match.

_Observation: I made two different playlists. One for a single disc taken from a multi-disc box set, and one for a number of tracks that I randomly selected. I proceeded to move the playlist out of their respective folders in order to break the list-to-track relationship, and then I copied the two test folders over to the roots of three different hard drives, plus one test-folder copied to a subdirectory on one of the drives. All the test playlists repaired properly. It should be noted that even the "Find Exact Matches" (binocular icon) action turned in **fully repaired playlists**. However, when the same "Find Exact Matches" (binocular icon) action is executed on previously made, older playlists, it still behaves as reported before — for all the releases tested up to now. This issue appears to be one that needs to be ironed out, and any suggestions on what the cause might be and how to proceed to nail it down, are welcome indeed._

**Screenshot:**

![image](https://user-images.githubusercontent.com/65730626/215511156-ff346f2f-b7df-47d5-9426-d9e5a49f67da.png)

**Question:**

**"Exact Matches Repair" (Ctrl + M):** Screenshot of action-window which opens. What action is required here, which is not already available elsewhere? Does it only open a playlist to repair in some way other than what is already available?

![image](https://user-images.githubusercontent.com/65730626/215513223-a2add561-bcfc-43da-a265-1901a687a08f.png)

_Originally posted by @touwys in https://github.com/Borewit/listFix/issues/28#issuecomment-1408845075_

**Comment by Borewit** [comment]
> Does it only open a playlist to repair in some way other than what is already available?

I checked the code, it seems to be redundant to the existing way of opening a playlist and then used the button (binocular icon). Very much in line how the coding is done, many redundant lines of code 🤣.

I have no problem stripping the menu option out, as I fail to see the added value.

**Comment by touwys** [comment]
@Borewit:

> I have no problem stripping the menu option out, as I fail to see the added value.

Would you be inclined to look at a few other proposals for possible app enhancements, once you have ironed out the operational wrinkles? There are some that I would like to share with you sometime ahead.

**Comment by Borewit** [comment]
> here are some that I would like to share with you sometime ahead.

Sure, feel free to raise issues for those.

**Comment by Borewit** [comment]
I think this is resolved
