### ISSUE TITLE
Add F2 Keyboard Shortcut

### ISSUE THREAD

**Issue by touwys** [Borewit/listFix#63]
Please add the F2 keyboard shortcut for quick access wherever renaming is required, for e.g. playlists and files. 

Work-flow and productivity are sure to gain from its addition.

**Comment by Borewit** [comment]
The dialog is also really weird, to first ask if the user want to rename a file.
Why not just cancel the rename dialog?

**Comment by Borewit** [comment]
And the default new filename is just the extension, better start with the old name....

![image](https://user-images.githubusercontent.com/23255260/218277687-8d34668c-1a0e-4757-9bb8-cba205a3241c.png)

**Comment by touwys** [comment]
> Why not just cancel the rename dialog?

Yes, agreed. If one renames a file, this intermediate step asking for confirmation, is rare. Simply rename and finish.
