### ISSUE TITLE
help running on Linux

### ISSUE THREAD

**Issue by vall77** [Borewit/listFix#65]
How do I run on Linux?
"Linux users can smbmount a network drive and then use the mount point as a media directory " this means nothing to me
also what happened to the.jar version of this program?

**Comment by Borewit** [comment]
> Linux users can smbmount a network drive and then use the mount point as a media directory " this means nothing to me

Part of the original documentation, something I did not write. I think what the author tries to say is, if you want access a Windows (SMB) file share, you can mount it under Linux. Mounting an SMB share  is something one can do, but certainly not a requirement.

What also needs to be better described is the different behavior running listFix() under Windows and Unix based systems.

> what happened to the.jar version of this program?

I have only focused on the Windows deployment so far. That has the runtime JRE now embedded in the installer, which eliminate to requirement to have a specific Java version installed.

**Comment by Borewit** [comment]
Resolved in https://github.com/Borewit/listFix/issues/16#issuecomment-1420458072
