### ISSUE TITLE
 Add "Save Layout" to "Confirm Close" Dialogue

### ISSUE THREAD

**Issue by touwys** [Borewit/listFix#70]
listFix() clears the Playlist Editor of all playlists upon closing — if the user chooses to discard changes made to the playlists. This action is available through the "Confirm Close" Dialogue.

A viable option here, would be to supplement the current actions in the "Confirm Close" Dialogue, with one that enables the user to preserve their current tabbed playlist layout until the app restart, when the saved playlist layout is automatically restored.

•

![Screenshot_20230207_163735](https://user-images.githubusercontent.com/65730626/217299652-6eaa35fe-de13-4f2d-944a-a35b1fd67cb3.png)

•

**Comment by Borewit** [comment]
We can store the playlist editors when we close the application, and restore those when the application is started. I am not in favor to bother the user with extra questions / options on exit.

**Comment by Borewit** [comment]
First this issue / PR pair needs to be completed:  
* #54
* #112

as that migrates existing application state the the JSON configuration file.

**Comment by touwys** [comment]
> We can store the playlist editors when we close the application, and restore those when the application is started. I am not in favor to bother the user with extra questions / options on exit.

I agree, it is superfluous. However, usually, this type of action would be made available as a programme _option_. (Maybe you could add that later on, as courtesy to the users who would prefer to start with a clean work interface?)
