### ISSUE TITLE
Incorrectly warns for unsaved changes in playlists

### ISSUE THREAD

**Issue by Borewit** [Borewit/listFix#74]
If a playlist is opened, and immediately closed (without changing / repairing) anything, the user is presented with a warning there are unsaved changes.

**Comment by touwys** [comment]
> If a playlist is opened, and immediately closed (without changing / repairing) anything, the user is presented with a warning there are unsaved changes.

Are you here referring to something other than the "Confirm Close" Dialogue in the screenshot below, which is all I get when repeating the same operation as yours? If it is, why remove it?

•••

!["Confirm Close" Dialogue](https://user-images.githubusercontent.com/65730626/218265939-22848305-6a62-43ec-b5f2-8a8f0f1ed792.png)
