### ISSUE TITLE
The "Open File Location" action is absent from the "Select Closest Matches" Dialogue

### ISSUE THREAD

**Issue by touwys** [Borewit/listFix#80]
**listFix_2.5.1-19**

The "Open File Location" action is absent from the "Select Closest Matches" **Dialogue** box. Please add it to extend the Preview>Play review of the replacement track?

**Comment by touwys** [comment]
@Borewit
 
Please, can you lend highest priority to this improvement over the others, followed by [Add "Save Layout" to "Confirm Close" Dialogue #70](https://github.com/Borewit/listFix/issues/70)? These are essential productivity tools.

What is meant by "good first issue"?

**Comment by Borewit** [comment]
> Please, can you lend highest priority to this improvement over the others, followed by https://github.com/Borewit/listFix/issues/70? These are essential productivity tools.

Sure. Note that I have done a lot of work behind the screen, aiming to clean the dependency tree. This resulted in a bit of D-tour, I adopted another ancient forgotten dependent open source project [lizzy](https://github.com/Borewit/lizzy). And it's kind of disaster in it's own way again. The aim is to be only dependent op open source components which are preferably already maintained, or at least in state that they are maintainable. 

> What is meant by "good first issue"?

This is a conventional label promoted by Github to mark issues (work) which can be easily picked up developers making their first steps in open source contribution: [good-first-issue](https://github.com/topics/good-first-issue).

**Comment by touwys** [comment]
Thank you, for your persistence, @Borewit. You are keeping very busy with project-development, and I hope you are successful with project [lizzy](https://github.com/Borewit/lizzy), too. Any, and all, the improvements you bring about to listFix() are always eagerly awaited.

> This is a conventional label promoted by Github to mark issues (work) which can be easily picked up developers making their first steps in open source contribution: [good-first-issue](https://github.com/topics/good-first-issue).

Yes, I read that part before posting, but wasn't sure about its consequence. In other words, it is like an open invitation-tag for other interested open-source developers to pick up on, inviting them to assist in the development of the current project.

**Comment by Borewit** [comment]
> Yes, I read that part before posting, but wasn't sure about its consequence. In other words, it is like an open invitation-tag for other interested open-source developers to pick up on, inviting them to assist in the development of the current project.

By being open source in GitHub that is already sort of the convention that you are open to contributions of other developers.  
While working on [Lizzy](https://github.com/Borewit/lizzy) I run into an issue of another project, so I created [an issue](https://github.com/gradle/gradle/issues/23963) and also provided the fix in a [PR](https://github.com/gradle/gradle/pull/23964).

That is how it works. But even if you know how to write code, you need get into the flow how we contribute projects and everyone has to start somewhere. So the idea is to start simple mark simple issue to attract and motivate more developers to contribute. For sure there is way more work to do then there are volunteers available to get the work done.

I wish most of the developers I work with professionally had more experience in open source contribution.
