### ISSUE TITLE
Weird behavior when using "Save As"

### ISSUE THREAD

**Issue by Borewit** [Borewit/listFix#91]
When using the _Save As_ to save a copy of a playlist under a different name:

1.  The playlist get saved with a double extension
1. The playlist name is not updated in the playlist editor (the tab).

Related to #79

**Comment by touwys** [comment]
**Build: listFix_2.5.1-PR89-26**

In fact, it saves the file with _two different types of extension, namely m3u and m3u8_

![image](https://user-images.githubusercontent.com/65730626/218315718-d2444691-caa5-4516-a46a-ec61e7f17cb2.png)
